#!/usr/bin/python
from argparse import ArgumentParser
import os
import multiprocessing

def bincue ():
  while not q.empty():
    cur_dir = q.get()
    os.chdir (cur_dir)
    os.popen ("shntool cue *.flac > foo.cue")
    os.popen ("shntool join *.flac")
 
# # Init Queue for found sudirectories
# q = multiprocessing.Queue()
# 
# # Grab all subdirectories within the current directory 
# search_sub ="find ./* -type d"
# 
# for subdir in os.popen (search_sub):
#   q.put (os.getcwd() + subdir[1:-1] + '/')
# 
# cores=multiprocessing.cpu_count()
# 
# for i in range (cores):
#   process = multiprocessing.Process(target=bincue, args=())
#   process.start()

def parse_media_source():
    pass

def main():
    parser_args = {"description": "PlayStation SoundScope player"}
    parser = ArgumentParser(**parser_args)
    media_source = {'args': ['media_source'],
                    'kwargs': {'nargs': '+',
                               'action': 'store',
                               'help': ("media source; "
                                        "default: current directory")}}
    parser.add_argument(*media_source['args'],
                        **media_source['kwargs'])

    args = parser.parse_args()

    print(args.media_source)
